export const initialData: any = {
  infos: {
    id: "",
    name: "",
    sex: "male" as "male",
    characterUrl: "",
    occupation: "",
    hitPoints: 0,
    magicPoints: 0,
    sanity: 0,
    inspiration: false,
  },
  attributes: {
    strength: 0,
    dexterity: 0,
    intelligence: 0,
    power: 0,
    constitution: 0,
    appearance: 0,
    size: 0,
    education: 0,
    luck: 0,
  },
  combat: [
    {
      id: "askçsdadsçdças",
      name: "Unarmed",
      iconUrl: "/weapons/fist.svg",
      skill: "Fighting(Brawl)",
      range: "-",
      damage: "1d3",
      attacks: "1",
      description:
        "Combat using only your fists or other unarmed techniques. Effective in close quarters but limited in damage.",
      properties: [
        "Can be used by any character without requiring special equipment.",
        "Damage is low but does not rely on external items.",
      ],
    },
  ],
  inventory: [],
  backstory: ``,
  skills: [
    {
      id: "saklsakdsalkdlska",
      name: "Accounting",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Anthropology",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Appraise",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Archaeology",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Charm",
      baseValue: 15,
      currentValue: 15,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Climb",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Credit Rating",
      baseValue: 0,
      currentValue: 0,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Cthulhu Mythos",
      baseValue: 0,
      currentValue: 0,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Disguise",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Dodge",
      baseValue: "half DEX",
      currentValue: 0,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Drive Auto",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Elec Repair",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Fast Talk",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Fighting(Brawl)",
      baseValue: 25,
      currentValue: 25,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Firearms(HG)",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Firearms(R/S)",
      baseValue: 25,
      currentValue: 25,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "First Aid",
      baseValue: 30,
      currentValue: 30,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "History",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Intimidate",
      baseValue: 15,
      currentValue: 15,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Jump",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Language(Own)",
      baseValue: "EDU",
      currentValue: 0,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Law",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Library Use",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Listen",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Locksmith",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Luck",
      baseValue: 65,
      currentValue: 65,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Mech Repair",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Medicine",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Natural World",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Navigate",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Occult",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Op Hv Machine",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Persuade",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Psychoanalysis",
      baseValue: 1,
      currentValue: 1,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Psychology",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Ride",
      baseValue: 5,
      currentValue: 5,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Sleight of Hand",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Spot Hidden",
      baseValue: 25,
      currentValue: 25,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Stealth",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Swim",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Throw",
      baseValue: 20,
      currentValue: 20,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Track",
      baseValue: 10,
      currentValue: 10,
      checked: false,
    },
  ],
}
