const firstNamesWithSex = [
  { name: "Arthur", sex: "male" },
  { name: "Eleanor", sex: "female" },
  { name: "Gideon", sex: "male" },
  { name: "Matilda", sex: "female" },
  { name: "Victor", sex: "male" },
  { name: "Beatrice", sex: "female" },
  { name: "Edgar", sex: "male" },
  { name: "Lillian", sex: "female" },
  { name: "Alistair", sex: "male" },
  { name: "Celeste", sex: "female" },
  { name: "Reginald", sex: "male" },
  { name: "Ophelia", sex: "female" },
  { name: "Nathaniel", sex: "male" },
  { name: "Seraphina", sex: "female" },
  { name: "Benedict", sex: "male" },
  { name: "Rosalind", sex: "female" },
  { name: "Ambrose", sex: "male" },
  { name: "Genevieve", sex: "female" },
  { name: "Percival", sex: "male" },
  { name: "Isadora", sex: "female" },
  { name: "Magnus", sex: "male" },
  { name: "Octavia", sex: "female" },
  { name: "Lucian", sex: "male" },
  { name: "Violet", sex: "female" },
  { name: "Theodore", sex: "male" },
  { name: "Amara", sex: "female" },
  { name: "Dorian", sex: "male" },
  { name: "Cassandra", sex: "female" },
  { name: "Leopold", sex: "male" },
  { name: "Selene", sex: "female" },
  { name: "Atticus", sex: "male" },
  { name: "Fiona", sex: "female" },
  { name: "Cassius", sex: "male" },
  { name: "Evangeline", sex: "female" },
  { name: "Maximilian", sex: "male" },
  { name: "Rowena", sex: "female" },
  { name: "Sylvester", sex: "male" },
  { name: "Arabella", sex: "female" },
  { name: "Hugo", sex: "male" },
  { name: "Morgana", sex: "female" },
  { name: "Edmund", sex: "male" },
  { name: "Lavinia", sex: "female" },
  { name: "Cornelius", sex: "male" },
  { name: "Helena", sex: "female" },
  { name: "Oswald", sex: "male" },
  { name: "Beatrix", sex: "female" },
  { name: "Ignatius", sex: "male" },
  { name: "Mirabel", sex: "female" },
  { name: "Ezekiel", sex: "male" },
  { name: "Cordelia", sex: "female" },
  { name: "Rupert", sex: "male" },
  { name: "Anastasia", sex: "female" },
  { name: "Phineas", sex: "male" },
  { name: "Josephine", sex: "female" },
  { name: "Balthazar", sex: "male" },
  { name: "Eulalia", sex: "female" },
  { name: "Bartholomew", sex: "male" },
  { name: "Celestine", sex: "female" },
  { name: "Thaddeus", sex: "male" },
  { name: "Isolde", sex: "female" },
]

const lastNames = [
  "Blackwood",
  "Hastings",
  "Ravensdale",
  "Whitmore",
  "Everstone",
  "Montague",
  "Holloway",
  "Fitzgerald",
  "Lancaster",
  "Thorne",
  "Fairchild",
  "Aldridge",
  "Harrington",
  "Sinclair",
  "Wyndham",
  "Davenport",
  "Ashford",
  "Hargreaves",
  "Pembroke",
  "Sterling",
  "Everhart",
  "Winslow",
  "Graves",
  "Halloway",
  "Carstairs",
  "Lockwood",
  "Fenwick",
  "Delacroix",
  "Sterlington",
  "Norwood",
  "Redgrave",
  "Beaumont",
  "Chamberlain",
  "Langley",
  "Valentine",
  "Fairfax",
  "Huntington",
  "Ashworth",
  "Belmont",
  "Wexford",
  "Weatherby",
  "Arkwright",
  "Dunmore",
  "Chadwick",
  "Wainwright",
  "Hollister",
  "Everleigh",
  "Ainsworth",
  "Haverford",
  "Bramwell",
  "Prescott",
  "Ellsworth",
  "Hemmingway",
  "Godfrey",
  "Tolliver",
  "Strathmore",
  "Wentworth",
  "Huxley",
  "Langston",
  "Cavendish",
]

export const generateRandomName = () => {
  const firstNameObj =
    firstNamesWithSex[Math.floor(Math.random() * firstNamesWithSex.length)]
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)]

  return {
    name: `${firstNameObj.name} ${lastName}`,
    sex: firstNameObj.sex,
  }
}
