const occupations = [
  "Private Investigator",
  "Professor of Occult History",
  "Forensic Doctor",
  "Sensationalist Journalist",
  "Amateur Occultist",
  "Librarian Specialized in Ancient Tomes",
  "Ruins Explorer",
  "Police Detective",
  "Wealthy Dilettante",
  "Anthropologist Obsessed with the Unknown",
  "Sailor Who Survived a Mysterious Shipwreck",
  "Astronomer Obsessed with Anomalous Constellations",
  "Fraudulent Medium (or maybe not...)",
  "Veteran Soldier of Forgotten Wars",
  "Priest Who Witnessed the Indescribable",
  "Psychoanalyst Who Treated a Very Strange Patient",
  "Archaeologist Who Found Something He Shouldn’t Have",
  "Pulp Fiction Writer Who Discovered the Truth",
  "Pharmacist with a Secret Formula",
  "Engineer Specialized in Underground Structures",
  "Cryptographer",
  "Folklorist",
  "Demonologist",
  "Historian of Lost Civilizations",
  "Psychic Investigator",
  "Blacksmith with a Hidden Past",
  "Cartographer of Forbidden Lands",
  "Mortician with Unusual Clients",
  "Exorcist",
  "Ship Captain Who Sailed Beyond the Known",
  "Antique Dealer Specializing in Cursed Objects",
  "Spy with Secrets Best Left Unknown",
  "Detective of the Unnatural",
  "Surgeon Who Operates on More Than Flesh",
  "Lighthouse Keeper Who Watches the Fog",
  "Stage Magician Who Knows Real Magic",
  "Grave Robber Turned Paranormal Expert",
  "Botanist Studying Unnatural Growths",
  "Cryptid Hunter",
  "Radio Host Who Hears More Than Static",
]

export const generateRandomOccupation = () => {
  return occupations[Math.floor(Math.random() * occupations.length)]
}
