export const currentSession = {
  id: "alsmdlsamdslamds",
  name: "Gabriel Sena",
  username: "#stardusteight",
  avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
}

export const playerCharacter = {
  player: {
    id: "alsmdlsamdslamds",
    name: "Gabriel Sena",
    username: "#stardusteight",
    avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
  },
  infos: {
    id: "asdsaas",
    name: "Erwin Farwell",
    sex: "male" as "male",
    characterUrl:
      "https://imgcdn.stablediffusionweb.com/2024/10/24/23cb7d83-7cac-43f6-8ac8-84c9cd8475a6.jpg",
    occupation: "Journalist and Private Detective",
    hitPoints: 75,
    magicPoints: 42,
    sanity: 22,
    inspiration: true,
  },
  attributes: {
    strength: 50,
    dexterity: 60,
    intelligence: 70,
    power: 65,
    constitution: 55,
    appearance: 60,
    size: 50,
    education: 70,
    luck: 42,
  },
  combat: [
    {
      id: "askçsdadsçdças",
      name: "Unarmed",
      iconUrl: "/weapons/fist.svg",
      skill: "Fighting(Brawl)",
      range: "-",
      damage: "1d3",
      attacks: "1",
      description:
        "Combat using only your fists or other unarmed techniques. Effective in close quarters but limited in damage.",
      properties: [
        "Can be used by any character without requiring special equipment.",
        "Damage is low but does not rely on external items.",
      ],
    },
    {
      id: "sdçdslçldaçls",
      name: "Kriegsbeil",
      iconUrl: "/weapons/kriegsbeil.svg",
      skill: "Fighting(Brawl)",
      range: "2m",
      damage: "1d20 + STR",
      attacks: "1",
      description:
        "The Kriegsbeil is a war axe of Germanic origin, commonly associated with heavy blades and a robust shaft. This weapon was designed for powerful strikes, capable of breaking through armor or dealing significant damage, but is generally limited to close combat.",
      properties: [
        "Has a chance to knock down or disarm the opponent.",
        "Heavy and requires the use of both hands to maximize its impact.",
      ],
    },
  ],
  skills: [
    {
      id: "saklsakdsalkdlska",
      name: "Accounting",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Anthropology",
      baseValue: 1,
      currentValue: 50,
      checked: true,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Appraise",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Archaeology",
      baseValue: 1,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Charm",
      baseValue: 15,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Climb",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Credit Rating",
      baseValue: 0,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Cthulhu Mythos",
      baseValue: 0,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Disguise",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Dodge",
      baseValue: "half DEX",
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Drive Auto",
      baseValue: 20,
      currentValue: 50,
      checked: true,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Elec Repair",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Fast Talk",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Fighting(Brawl)",
      baseValue: 25,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Firearms(HG)",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Firearms(R/S)",
      baseValue: 25,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "First Aid",
      baseValue: 30,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "History",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Intimidate",
      baseValue: 15,
      currentValue: 50,
      checked: true,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Jump",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Language(Own)",
      baseValue: "EDU",
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Law",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Library Use",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Listen",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Locksmith",
      baseValue: 1,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Luck",
      baseValue: 65,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Mech Repair",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Medicine",
      baseValue: 1,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Natural World",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Navigate",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Occult",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Op Hv Machine",
      baseValue: 1,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Persuade",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Psychoanalysis",
      baseValue: 1,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Psychology",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Ride",
      baseValue: 5,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Sleight of Hand",
      baseValue: 10,
      currentValue: 50,
      checked: true,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Spot Hidden",
      baseValue: 25,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Stealth",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Swim",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Throw",
      baseValue: 20,
      currentValue: 50,
      checked: false,
    },
    {
      id: "saklsakdsalkdlska",
      name: "Track",
      baseValue: 10,
      currentValue: 50,
      checked: false,
    },
  ],
}

export const characters: any = [
  {
    player: {
      id: "alsmdlsamdslamds",
      name: "Gabriel Sena",
      username: "#stardusteight",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "asdsaas",
      name: "Erwin Farwell",
      sex: "male" as "male",
      characterUrl:
        "https://imgcdn.stablediffusionweb.com/2024/10/24/23cb7d83-7cac-43f6-8ac8-84c9cd8475a6.jpg",
      occupation: "Journalist and Private Detective",
      hitPoints: 75,
      magicPoints: 42,
      sanity: 22,
      inspiration: true,
    },
    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
      luck: 42,
    },
    combat: [
      {
        id: "askçsdadsçdças",
        name: "Unarmed",
        iconUrl: "/weapons/fist.svg",
        skill: "Fighting(Brawl)",
        range: "-",
        damage: "1d3",
        attacks: "1",
        description:
          "Combat using only your fists or other unarmed techniques. Effective in close quarters but limited in damage.",
        properties: [
          "Can be used by any character without requiring special equipment.",
          "Damage is low but does not rely on external items.",
        ],
      },
      {
        id: "sdçdslçldaçls",
        name: "Kriegsbeil",
        iconUrl: "/weapons/kriegsbeil.svg",
        skill: "Fighting(Brawl)",
        range: "2m",
        damage: "1d20 + STR",
        attacks: "1",
        description:
          "The Kriegsbeil is a war axe of Germanic origin, commonly associated with heavy blades and a robust shaft. This weapon was designed for powerful strikes, capable of breaking through armor or dealing significant damage, but is generally limited to close combat.",
        properties: [
          "Has a chance to knock down or disarm the opponent.",
          "Heavy and requires the use of both hands to maximize its impact.",
        ],
      },
    ],
    skills: [
      {
        id: "saklsakdsalkdlska",
        name: "Accounting",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Anthropology",
        baseValue: 1,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Appraise",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Archaeology",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Charm",
        baseValue: 15,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Climb",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Credit Rating",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Cthulhu Mythos",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Disguise",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Drive Auto",
        baseValue: 20,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Elec Repair",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fast Talk",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(HG)",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "First Aid",
        baseValue: 30,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "History",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Intimidate",
        baseValue: 15,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Jump",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Law",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Library Use",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Listen",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Locksmith",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Luck",
        baseValue: 65,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Mech Repair",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Medicine",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Natural World",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Navigate",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Occult",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Op Hv Machine",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Persuade",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychology",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Ride",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Spot Hidden",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Stealth",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Swim",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Throw",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Track",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
    ],
  },
  {
    player: {
      id: "asnshlkasjlalssla",
      name: "Juan Paul",
      username: "#paullz",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "asfafsafv",
      name: "Erik Bjorn",
      sex: "male" as "male",
      characterUrl:
        "https://neural.love/cdn/thumbnails/1eed6701-3f10-66ae-a3ea-41b70a0743ac/eeb65884-de3b-5ffc-9982-79cfe16f394b.webp?Expires=1767225599&Signature=tnQgxe3HIRNHu4D532pE79A2nbqUhNwYrzKXOsl-ZX9uqsiDQY1orBDBv1pBmKVfHtCWwp9N31Q7wP4n2S~BKTJRHElZheN-DJU5Q3nHRIiXqvXdxKBYnD7ZH3Mcjl6n9RuxIy5YywbWqvTIs05HYX13SmDMOBx4sCaJvD4MBovknJ1OWL~1txwStM7fNnsyLKf8j857Kci1OLDKuDeJyRgKzQryixLSt-KB7lknK2tXGeAA~XW31yW9dbVhw0oeuXwhJAXYtezI9pcGaBHmm2sPtr3BMM7mJtkK-arna11zegqXaYVEeCsdRxQCwTHQUuApPYk0Kc6OHZ4eTnr42w__&Key-Pair-Id=K2RFTOXRBNSROX",
      occupation: "Journalist and Private Detective",
      hitPoints: 150,
      magicPoints: 0,
      sanity: 100,
      inspiration: false,
    },

    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
      luck: 42,
    },
    combat: [
      {
        id: "askçsdadsçdças",
        name: "Unarmed",
        iconUrl: "/weapons/fist.svg",
        skill: "Fighting(Brawl)",
        range: "-",
        damage: "1d3",
        attacks: "1",
        description:
          "Combat using only your fists or other unarmed techniques. Effective in close quarters but limited in damage.",
        properties: [
          "Can be used by any character without requiring special equipment.",
          "Damage is low but does not rely on external items.",
        ],
      },
      //   {
      //     id: "assldksaldskl",
      //     name: "Morgenstern",
      //     iconUrl: "/weapons/morgenstern.svg",
      //     skill: "Fighting(Brawl)",
      //     range: "2m",
      //     damage: "1d20 + STR",
      //     attacks: "1",
      //     description:
      //       "The Morgenstern, also known as the morning star, is a blunt weapon with a spiked (or pointed) head attached to a shaft. It was designed to deal severe damage with crushing blows and can penetrate weaker armors.",
      //     properties: [
      //       "Ideal for blunt attacks that cause damage to denser areas, such as heavy armor.",
      //       "Chance to deal additional damage when attacking targets with weaker armor.",
      //     ],
      //   },
    ],
    skills: [
      {
        id: "saklsakdsalkdlska",
        name: "Accounting",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Anthropology",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Appraise",
        baseValue: 5,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Archaeology",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Charm",
        baseValue: 15,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Climb",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Credit Rating",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Cthulhu Mythos",
        baseValue: 0,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Disguise",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Drive Auto",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Elec Repair",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fast Talk",
        baseValue: 5,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(HG)",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "First Aid",
        baseValue: 30,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "History",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Intimidate",
        baseValue: 15,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Jump",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Law",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Library Use",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Listen",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Locksmith",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Luck",
        baseValue: 65,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Mech Repair",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Medicine",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Natural World",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Navigate",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Occult",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Op Hv Machine",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Persuade",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychology",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Ride",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Spot Hidden",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Stealth",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Swim",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Throw",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Track",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
    ],
  },
  {
    player: {
      id: "sadjsaljdsaljdlsj",
      name: "Fernanda Sena",
      username: "#fevient",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "aksalskals",
      name: "Lizabeth White",
      sex: "female" as "female",
      characterUrl:
        "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f2664fbe-b0bd-454c-bfe6-6e930a07fc49/dh1yf6m-9a50d508-4a14-4f63-9a0b-b4339f5d284a.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2YyNjY0ZmJlLWIwYmQtNDU0Yy1iZmU2LTZlOTMwYTA3ZmM0OVwvZGgxeWY2bS05YTUwZDUwOC00YTE0LTRmNjMtOWEwYi1iNDMzOWY1ZDI4NGEuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.VNORNfSflxfLfH0SH-r1mLEM8eyB8LsRfinCHZuP5Jc",
      occupation: "Journalist and Private Detective",
      hitPoints: 100,
      magicPoints: 12,
      sanity: 84,
      inspiration: true,
    },
    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
      luck: 42,
    },
    combat: [
      {
        id: "askçsdadsçdças",
        name: "Unarmed",
        iconUrl: "/weapons/fist.svg",
        skill: "Fighting(Brawl)",
        range: "-",
        damage: "1d3",
        attacks: "1",
        description:
          "Combat using only your fists or other unarmed techniques. Effective in close quarters but limited in damage.",
        properties: [
          "Can be used by any character without requiring special equipment.",
          "Damage is low but does not rely on external items.",
        ],
      },
      {
        id: "sakçsaksçkdsçads",
        name: "Schwerer Dolch",
        iconUrl: "/weapons/schwerer-dolch.svg",
        skill: "Fighting(Brawl)",
        range: "0.7m",
        damage: "1d8 + STR",
        attacks: "1",
        description:
          "The Schwerer Dolch is a heavier and larger version of the standard dagger. It has more reach and can deal more damage with each strike, making it suitable for direct combat.",
        properties: [
          "Heavier than a regular dagger, offering more damage.",
          "Longer reach, effective for close-quarters combat.",
          "Good for both stabbing and slashing.",
        ],
      },
      {
        id: "laslçvdskçkd",
        name: "Schwerer Dolch",
        iconUrl: "/weapons/schwerer-dolch.svg",
        skill: "Fighting(Brawl)",
        range: "0.7m",
        damage: "1d8 + STR",
        attacks: "1",
        description:
          "The Schwerer Dolch is a heavier and larger version of the standard dagger. It has more reach and can deal more damage with each strike, making it suitable for direct combat.",
        properties: [
          "Heavier than a regular dagger, offering more damage.",
          "Longer reach, effective for close-quarters combat.",
          "Good for both stabbing and slashing.",
        ],
      },
    ],
    skills: [
      {
        id: "saklsakdsalkdlska",
        name: "Accounting",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Anthropology",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Appraise",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Archaeology",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Charm",
        baseValue: 15,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Climb",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Credit Rating",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Cthulhu Mythos",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Disguise",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Drive Auto",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Elec Repair",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fast Talk",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(HG)",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "First Aid",
        baseValue: 30,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "History",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Intimidate",
        baseValue: 15,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Jump",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Law",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Library Use",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Listen",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Locksmith",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Luck",
        baseValue: 65,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Mech Repair",
        baseValue: 10,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Medicine",
        baseValue: 1,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Natural World",
        baseValue: 10,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Navigate",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Occult",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Op Hv Machine",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Persuade",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Psychology",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Ride",
        baseValue: 5,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Spot Hidden",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Stealth",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Swim",
        baseValue: 20,
        currentValue: 50,
        checked: false,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Throw",
        baseValue: 20,
        currentValue: 50,
        checked: true,
      },
      {
        id: "saklsakdsalkdlska",
        name: "Track",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
    ],
  },
]
