export const currentSession = {
  id: "alsmdlsamdslamds",
  name: "Gabriel Sena",
  username: "#stardusteight",
  avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
}

export const playerCharacter = {
  player: {
    id: "alsmdlsamdslamds",
    name: "Gabriel Sena",
    username: "#stardusteight",
    avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
  },
  infos: {
    id: "asdsaas",
    name: "Erwin Farwell",
    sex: "male" as "male",
    characterUrl:
      "https://imgcdn.stablediffusionweb.com/2024/10/24/23cb7d83-7cac-43f6-8ac8-84c9cd8475a6.jpg",
    occupation: "Journalist and Private Detective",
    hitPoints: 75,
    magicPoints: 42,
    sanity: 22,
  },
  attributes: {
    strength: 50,
    dexterity: 60,
    intelligence: 70,
    power: 65,
    constitution: 55,
    appearance: 60,
    size: 50,
    education: 70,
  },
  skills: [
    { name: "Accounting", baseValue: 5, currentValue: 50, checked: false },
    { name: "Anthropology", baseValue: 1, currentValue: 50, checked: true },
    { name: "Appraise", baseValue: 5, currentValue: 50, checked: false },
    { name: "Archaeology", baseValue: 1, currentValue: 50, checked: false },
    { name: "Charm", baseValue: 15, currentValue: 50, checked: false },
    { name: "Climb", baseValue: 20, currentValue: 50, checked: false },
    { name: "Credit Rating", baseValue: 0, currentValue: 50, checked: false },
    { name: "Cthulhu Mythos", baseValue: 0, currentValue: 50, checked: false },
    { name: "Disguise", baseValue: 5, currentValue: 50, checked: false },
    { name: "Dodge", baseValue: "half DEX", currentValue: 50, checked: false },
    { name: "Drive Auto", baseValue: 20, currentValue: 50, checked: true },
    { name: "Elec Repair", baseValue: 10, currentValue: 50, checked: false },
    { name: "Fast Talk", baseValue: 5, currentValue: 50, checked: false },
    {
      name: "Fighting(Brawl)",
      baseValue: 25,
      currentValue: 50,
      checked: false,
    },
    { name: "Firearms(HG)", baseValue: 20, currentValue: 50, checked: false },
    { name: "Firearms(R/S)", baseValue: 25, currentValue: 50, checked: false },
    { name: "First Aid", baseValue: 30, currentValue: 50, checked: false },
    { name: "History", baseValue: 5, currentValue: 50, checked: false },
    { name: "Intimidate", baseValue: 15, currentValue: 50, checked: true },
    { name: "Jump", baseValue: 20, currentValue: 50, checked: false },
    {
      name: "Language(Own)",
      baseValue: "EDU",
      currentValue: 50,
      checked: false,
    },
    { name: "Law", baseValue: 5, currentValue: 50, checked: false },
    { name: "Library Use", baseValue: 20, currentValue: 50, checked: false },
    { name: "Listen", baseValue: 20, currentValue: 50, checked: false },
    { name: "Locksmith", baseValue: 1, currentValue: 50, checked: false },
    { name: "Luck", baseValue: 65, currentValue: 50, checked: false },
    { name: "Mech Repair", baseValue: 10, currentValue: 50, checked: false },
    { name: "Medicine", baseValue: 1, currentValue: 50, checked: false },
    { name: "Natural World", baseValue: 10, currentValue: 50, checked: false },
    { name: "Navigate", baseValue: 10, currentValue: 50, checked: false },
    { name: "Occult", baseValue: 5, currentValue: 50, checked: false },
    { name: "Op Hv Machine", baseValue: 1, currentValue: 50, checked: false },
    { name: "Persuade", baseValue: 10, currentValue: 50, checked: false },
    { name: "Psychoanalysis", baseValue: 1, currentValue: 50, checked: false },
    { name: "Psychology", baseValue: 10, currentValue: 50, checked: false },
    { name: "Ride", baseValue: 5, currentValue: 50, checked: false },
    { name: "Sleight of Hand", baseValue: 10, currentValue: 50, checked: true },
    { name: "Spot Hidden", baseValue: 25, currentValue: 50, checked: false },
    { name: "Stealth", baseValue: 20, currentValue: 50, checked: false },
    { name: "Swim", baseValue: 20, currentValue: 50, checked: false },
    { name: "Throw", baseValue: 20, currentValue: 50, checked: false },
    { name: "Track", baseValue: 10, currentValue: 50, checked: false },
  ],
}

export const characters = [
  {
    player: {
      id: "alsmdlsamdslamds",
      name: "Gabriel Sena",
      username: "#stardusteight",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "asdsaas",
      name: "Erwin Farwell",
      sex: "male" as "male",
      characterUrl:
        "https://imgcdn.stablediffusionweb.com/2024/10/24/23cb7d83-7cac-43f6-8ac8-84c9cd8475a6.jpg",
      occupation: "Journalist and Private Detective",
      hitPoints: 75,
      magicPoints: 42,
      sanity: 22,
    },
    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
    },
    skills: [
      { name: "Accounting", baseValue: 5, currentValue: 50, checked: false },
      { name: "Anthropology", baseValue: 1, currentValue: 50, checked: true },
      { name: "Appraise", baseValue: 5, currentValue: 50, checked: false },
      { name: "Archaeology", baseValue: 1, currentValue: 50, checked: false },
      { name: "Charm", baseValue: 15, currentValue: 50, checked: false },
      { name: "Climb", baseValue: 20, currentValue: 50, checked: false },
      { name: "Credit Rating", baseValue: 0, currentValue: 50, checked: false },
      {
        name: "Cthulhu Mythos",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      { name: "Disguise", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      { name: "Drive Auto", baseValue: 20, currentValue: 50, checked: true },
      { name: "Elec Repair", baseValue: 10, currentValue: 50, checked: false },
      { name: "Fast Talk", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      { name: "Firearms(HG)", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      { name: "First Aid", baseValue: 30, currentValue: 50, checked: false },
      { name: "History", baseValue: 5, currentValue: 50, checked: false },
      { name: "Intimidate", baseValue: 15, currentValue: 50, checked: true },
      { name: "Jump", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      { name: "Law", baseValue: 5, currentValue: 50, checked: false },
      { name: "Library Use", baseValue: 20, currentValue: 50, checked: false },
      { name: "Listen", baseValue: 20, currentValue: 50, checked: false },
      { name: "Locksmith", baseValue: 1, currentValue: 50, checked: false },
      { name: "Luck", baseValue: 65, currentValue: 50, checked: false },
      { name: "Mech Repair", baseValue: 10, currentValue: 50, checked: false },
      { name: "Medicine", baseValue: 1, currentValue: 50, checked: false },
      {
        name: "Natural World",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      { name: "Navigate", baseValue: 10, currentValue: 50, checked: false },
      { name: "Occult", baseValue: 5, currentValue: 50, checked: false },
      { name: "Op Hv Machine", baseValue: 1, currentValue: 50, checked: false },
      { name: "Persuade", baseValue: 10, currentValue: 50, checked: false },
      {
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      { name: "Psychology", baseValue: 10, currentValue: 50, checked: false },
      { name: "Ride", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: true,
      },
      { name: "Spot Hidden", baseValue: 25, currentValue: 50, checked: false },
      { name: "Stealth", baseValue: 20, currentValue: 50, checked: false },
      { name: "Swim", baseValue: 20, currentValue: 50, checked: false },
      { name: "Throw", baseValue: 20, currentValue: 50, checked: false },
      { name: "Track", baseValue: 10, currentValue: 50, checked: false },
    ],
  },
  {
    player: {
      id: "asnshlkasjlalssla",
      name: "Juan Paul",
      username: "#paullz",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "asfafsafv",
      name: "Erik Bjorn ",
      sex: "male" as "male",
      characterUrl:
        "https://neural.love/cdn/thumbnails/1eed6701-3f10-66ae-a3ea-41b70a0743ac/eeb65884-de3b-5ffc-9982-79cfe16f394b.webp?Expires=1767225599&Signature=tnQgxe3HIRNHu4D532pE79A2nbqUhNwYrzKXOsl-ZX9uqsiDQY1orBDBv1pBmKVfHtCWwp9N31Q7wP4n2S~BKTJRHElZheN-DJU5Q3nHRIiXqvXdxKBYnD7ZH3Mcjl6n9RuxIy5YywbWqvTIs05HYX13SmDMOBx4sCaJvD4MBovknJ1OWL~1txwStM7fNnsyLKf8j857Kci1OLDKuDeJyRgKzQryixLSt-KB7lknK2tXGeAA~XW31yW9dbVhw0oeuXwhJAXYtezI9pcGaBHmm2sPtr3BMM7mJtkK-arna11zegqXaYVEeCsdRxQCwTHQUuApPYk0Kc6OHZ4eTnr42w__&Key-Pair-Id=K2RFTOXRBNSROX",
      occupation: "Journalist and Private Detective",
      hitPoints: 150,
      magicPoints: 0,
      sanity: 100,
    },
    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
    },
    skills: [
      { name: "Accounting", baseValue: 5, currentValue: 50, checked: false },
      { name: "Anthropology", baseValue: 1, currentValue: 50, checked: false },
      { name: "Appraise", baseValue: 5, currentValue: 50, checked: true },
      { name: "Archaeology", baseValue: 1, currentValue: 50, checked: false },
      { name: "Charm", baseValue: 15, currentValue: 50, checked: false },
      { name: "Climb", baseValue: 20, currentValue: 50, checked: false },
      { name: "Credit Rating", baseValue: 0, currentValue: 50, checked: false },
      { name: "Cthulhu Mythos", baseValue: 0, currentValue: 50, checked: true },
      { name: "Disguise", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      { name: "Drive Auto", baseValue: 20, currentValue: 50, checked: false },
      { name: "Elec Repair", baseValue: 10, currentValue: 50, checked: false },
      { name: "Fast Talk", baseValue: 5, currentValue: 50, checked: true },
      {
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: true,
      },
      { name: "Firearms(HG)", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      { name: "First Aid", baseValue: 30, currentValue: 50, checked: false },
      { name: "History", baseValue: 5, currentValue: 50, checked: false },
      { name: "Intimidate", baseValue: 15, currentValue: 50, checked: false },
      { name: "Jump", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      { name: "Law", baseValue: 5, currentValue: 50, checked: false },
      { name: "Library Use", baseValue: 20, currentValue: 50, checked: false },
      { name: "Listen", baseValue: 20, currentValue: 50, checked: false },
      { name: "Locksmith", baseValue: 1, currentValue: 50, checked: false },
      { name: "Luck", baseValue: 65, currentValue: 50, checked: false },
      { name: "Mech Repair", baseValue: 10, currentValue: 50, checked: false },
      { name: "Medicine", baseValue: 1, currentValue: 50, checked: false },
      {
        name: "Natural World",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      { name: "Navigate", baseValue: 10, currentValue: 50, checked: false },
      { name: "Occult", baseValue: 5, currentValue: 50, checked: false },
      { name: "Op Hv Machine", baseValue: 1, currentValue: 50, checked: false },
      { name: "Persuade", baseValue: 10, currentValue: 50, checked: false },
      {
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      { name: "Psychology", baseValue: 10, currentValue: 50, checked: false },
      { name: "Ride", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      { name: "Spot Hidden", baseValue: 25, currentValue: 50, checked: false },
      { name: "Stealth", baseValue: 20, currentValue: 50, checked: false },
      { name: "Swim", baseValue: 20, currentValue: 50, checked: false },
      { name: "Throw", baseValue: 20, currentValue: 50, checked: false },
      { name: "Track", baseValue: 10, currentValue: 50, checked: false },
    ],
  },
  {
    player: {
      id: "sadjsaljdsaljdlsj",
      name: "Fernanda Sena",
      username: "#fevient",
      avatarUrl: "https://avatars.githubusercontent.com/u/87643260?v=4",
    },
    infos: {
      id: "aksalskals",
      name: "Lizabeth White",
      player: "Gabriel Sena",
      sex: "female" as "female",
      characterUrl:
        "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f2664fbe-b0bd-454c-bfe6-6e930a07fc49/dh1yf6m-9a50d508-4a14-4f63-9a0b-b4339f5d284a.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2YyNjY0ZmJlLWIwYmQtNDU0Yy1iZmU2LTZlOTMwYTA3ZmM0OVwvZGgxeWY2bS05YTUwZDUwOC00YTE0LTRmNjMtOWEwYi1iNDMzOWY1ZDI4NGEuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.VNORNfSflxfLfH0SH-r1mLEM8eyB8LsRfinCHZuP5Jc",
      occupation: "Journalist and Private Detective",
      hitPoints: 100,
      magicPoints: 12,
      sanity: 84,
    },
    attributes: {
      strength: 50,
      dexterity: 60,
      intelligence: 70,
      power: 65,
      constitution: 55,
      appearance: 60,
      size: 50,
      education: 70,
    },
    skills: [
      { name: "Accounting", baseValue: 5, currentValue: 50, checked: false },
      { name: "Anthropology", baseValue: 1, currentValue: 50, checked: false },
      { name: "Appraise", baseValue: 5, currentValue: 50, checked: false },
      { name: "Archaeology", baseValue: 1, currentValue: 50, checked: false },
      { name: "Charm", baseValue: 15, currentValue: 50, checked: true },
      { name: "Climb", baseValue: 20, currentValue: 50, checked: false },
      { name: "Credit Rating", baseValue: 0, currentValue: 50, checked: false },
      {
        name: "Cthulhu Mythos",
        baseValue: 0,
        currentValue: 50,
        checked: false,
      },
      { name: "Disguise", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Dodge",
        baseValue: "half DEX",
        currentValue: 50,
        checked: false,
      },
      { name: "Drive Auto", baseValue: 20, currentValue: 50, checked: false },
      { name: "Elec Repair", baseValue: 10, currentValue: 50, checked: false },
      { name: "Fast Talk", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Fighting(Brawl)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      { name: "Firearms(HG)", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Firearms(R/S)",
        baseValue: 25,
        currentValue: 50,
        checked: false,
      },
      { name: "First Aid", baseValue: 30, currentValue: 50, checked: false },
      { name: "History", baseValue: 5, currentValue: 50, checked: false },
      { name: "Intimidate", baseValue: 15, currentValue: 50, checked: false },
      { name: "Jump", baseValue: 20, currentValue: 50, checked: false },
      {
        name: "Language(Own)",
        baseValue: "EDU",
        currentValue: 50,
        checked: false,
      },
      { name: "Law", baseValue: 5, currentValue: 50, checked: false },
      { name: "Library Use", baseValue: 20, currentValue: 50, checked: false },
      { name: "Listen", baseValue: 20, currentValue: 50, checked: false },
      { name: "Locksmith", baseValue: 1, currentValue: 50, checked: false },
      { name: "Luck", baseValue: 65, currentValue: 50, checked: false },
      { name: "Mech Repair", baseValue: 10, currentValue: 50, checked: true },
      { name: "Medicine", baseValue: 1, currentValue: 50, checked: true },
      { name: "Natural World", baseValue: 10, currentValue: 50, checked: true },
      { name: "Navigate", baseValue: 10, currentValue: 50, checked: false },
      { name: "Occult", baseValue: 5, currentValue: 50, checked: false },
      { name: "Op Hv Machine", baseValue: 1, currentValue: 50, checked: false },
      { name: "Persuade", baseValue: 10, currentValue: 50, checked: false },
      {
        name: "Psychoanalysis",
        baseValue: 1,
        currentValue: 50,
        checked: false,
      },
      { name: "Psychology", baseValue: 10, currentValue: 50, checked: false },
      { name: "Ride", baseValue: 5, currentValue: 50, checked: false },
      {
        name: "Sleight of Hand",
        baseValue: 10,
        currentValue: 50,
        checked: false,
      },
      { name: "Spot Hidden", baseValue: 25, currentValue: 50, checked: false },
      { name: "Stealth", baseValue: 20, currentValue: 50, checked: false },
      { name: "Swim", baseValue: 20, currentValue: 50, checked: false },
      { name: "Throw", baseValue: 20, currentValue: 50, checked: true },
      { name: "Track", baseValue: 10, currentValue: 50, checked: false },
    ],
  },
]
